### ISSUE TITLE
Doesn't work anymore :'( 

### ISSUE THREAD

**Issue by sdwvit** [valeriangalliat/ytmdl#1]
```
> MacBook-Pro-Viktor:DonsTunes viktormusienko$ ytmdl https://music.youtube.com/playlist?list=UUYY_YLVWFI_IZ51Eu6x9bgA
(node:77000) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'payloads' of undefined
    at indexPayloads (/Users/viktormusienko/WebstormProjects/ytmdl/youtube-music.js:54:40)
    at getAlbum (/Users/viktormusienko/WebstormProjects/ytmdl/youtube-music.js:68:17)
    at <anonymous>
(node:77000) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:77000) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by valeriangalliat** [comment]
Oh, looks like the whole album is exclusive to premium members, the songs are marked as "unavailable" otherwise. This script only supports downloading "free" content for now.

Feel free to do a PR implementing some kind of authentication or a way to inject cookies from your browser so it can access the premium songs. I can't do it myself as I don't have a premium account. :/

**Comment by valeriangalliat** [comment]
Or DM me your cookies so I can test myself. :trollface:

**Comment by sdwvit** [comment]
@valeriangalliat I don't have premium, download does not work for example in readme neither

**Comment by sdwvit** [comment]
I'll definitely take a look later, in the meanwhile I used 
https://www.mediahuman.com/?mh_product=youtubetomp3&mh_version=3.9.9.13&mh_source=app-about
<img width="174" alt="Screen Shot 2019-03-26 at 11 57 07 PM" src="https://user-images.githubusercontent.com/8777372/55049506-e6097380-5022-11e9-8273-7199d64f7a9e.png">

**Comment by valeriangalliat** [comment]
Cool!

I just pushed https://github.com/valeriangalliat/ytmdl/commit/925e13ed6f8d49dcd89114c2186d3ad63d569544, this makes the album from the readme download properly again.

However for your particular playlist, the script currently doesn't support playlists so it's still not gonna work (I'd recommend using [youtube-dl](https://ytdl-org.github.io/youtube-dl/index.html) for playlists, awesome tool).
